import "server-only";

/**
 * Dependency-free SMS / OTP delivery. No new npm package.
 *
 * Two entry points:
 *   sendOtpSms()  - the OTP path. Uses MSG91's OTP API, which renders a
 *                   DLT-approved template server-side.
 *   sendSms()     - generic text SMS (Twilio, or MSG91 Flow with a
 *                   DLT-approved flow template).
 *
 * WHY OTP DOES NOT GO THROUGH sendSms():
 * Under India's TRAI/DLT regime you cannot send arbitrary SMS text. Every
 * message body must match a template registered on the DLT portal and
 * approved against your entity, and the operator scrubs anything that does
 * not. So the OTP path sends a template id plus the code as a variable, and
 * the gateway assembles the text - our own copy of the wording is never
 * transmitted.
 *
 * Debug help for non-production: when `OTP_DEBUG_RETURN` is "1" AND
 * NODE_ENV !== "production", the OTP send route echoes the code in its JSON
 * response so the flow can be tested without spending SMS credits. This is
 * force-disabled in production regardless of the env var.
 */
export function otpDebugReturnEnabled(): boolean {
  return process.env.NODE_ENV !== "production" && process.env.OTP_DEBUG_RETURN === "1";
}

export type SmsResult = { delivered: boolean; reason?: string };

/** 10-digit Indian numbers get the country code; anything else is passed through. */
function toE164Digits(raw: string): string {
  const digits = raw.replace(/\D/g, "");
  return digits.length === 10 ? `91${digits}` : digits;
}

/**
 * MSG91 answers with HTTP 200 for a lot of failures and puts the real
 * outcome in the body as `{"type":"error","message":"..."}`. Checking
 * `res.ok` alone therefore reports undelivered messages as delivered, which
 * is how an OTP flow ends up silently dropping codes while looking healthy.
 */
async function readMsg91Result(res: Response, prefix: string): Promise<SmsResult> {
  let body: unknown;
  try {
    body = await res.json();
  } catch {
    return res.ok
      ? { delivered: false, reason: `${prefix}_UNPARSEABLE_RESPONSE` }
      : { delivered: false, reason: `${prefix}_${res.status}` };
  }

  const payload = body as { type?: string; message?: unknown; request_id?: string };

  if (!res.ok) {
    const detail = typeof payload?.message === "string" ? payload.message : `HTTP ${res.status}`;
    return { delivered: false, reason: `${prefix}_${res.status}: ${detail}` };
  }
  if (payload?.type === "success") {
    return { delivered: true };
  }

  const detail =
    typeof payload?.message === "string" ? payload.message : JSON.stringify(payload ?? {});
  return { delivered: false, reason: `${prefix}_REJECTED: ${detail}` };
}

/**
 * Sends a one-time code through MSG91's OTP API.
 *
 * The code is generated, hashed and stored by us (see @/lib/otp) and merely
 * handed to MSG91 for delivery via `otp`, so verification stays local -
 * MSG91's own verify endpoint is deliberately not used. That keeps the
 * bcrypt-hashed challenge, the attempt counter and the rate limits as the
 * single source of truth, and means a gateway swap never changes how a code
 * is checked.
 *
 * Cost: one OTP credit per successful call. The caller is expected to have
 * passed checkSendRateLimit() first (45s resend cooldown, 5/hour per phone,
 * 15/hour per IP) - without that, a scripted signup form can drain a
 * prepaid balance in minutes.
 */
export async function sendOtpSms(opts: {
  to: string;
  code: string;
  ttlMinutes: number;
}): Promise<SmsResult> {
  const mobile = toE164Digits(opts.to);

  const authkey = process.env.MSG91_AUTHKEY;
  const templateId = process.env.MSG91_OTP_TEMPLATE_ID;

  if (authkey && templateId) {
    try {
      const url = new URL("https://control.msg91.com/api/v5/otp");
      url.searchParams.set("template_id", templateId);
      url.searchParams.set("mobile", mobile);
      // Our code, not one generated by MSG91 - see the note above.
      url.searchParams.set("otp", opts.code);
      url.searchParams.set("otp_expiry", String(opts.ttlMinutes));
      // Ask for the real send result in this response instead of a queued ack,
      // so a rejected template or an empty balance surfaces immediately.
      url.searchParams.set("realTimeResponse", "1");

      const res = await fetch(url, {
        method: "POST",
        headers: { authkey, "Content-Type": "application/json" },
        body: "{}",
        cache: "no-store",
      });

      return await readMsg91Result(res, "MSG91_OTP");
    } catch (err) {
      console.error("[sms] MSG91 OTP request failed:", err);
      return { delivered: false, reason: "MSG91_OTP_EXCEPTION" };
    }
  }

  if (authkey && !templateId) {
    // Failing loudly beats falling back to a plain-text send that DLT will
    // scrub anyway.
    return { delivered: false, reason: "MSG91_OTP_TEMPLATE_ID_MISSING" };
  }

  // No MSG91 - fall back to the generic sender (Twilio, or the dev log path)
  // where composing our own text is allowed.
  return sendSms({
    to: opts.to,
    text: `${opts.code} is your Atomic Pathshala verification code. Valid for ${opts.ttlMinutes} minutes. Do not share it.`,
  });
}

/**
 * Generic text SMS.
 *
 * For MSG91 this needs a DLT-approved *flow* template (MSG91_FLOW_TEMPLATE_ID)
 * whose body carries a single `##var##` placeholder; the text is passed as
 * that variable. Without a template id the MSG91 path is skipped rather than
 * attempted, because a free-text send under DLT is rejected by the operator
 * and would otherwise be reported as success.
 */
export async function sendSms(opts: { to: string; text: string }): Promise<SmsResult> {
  const mobile = toE164Digits(opts.to);

  // --- MSG91 (Flow API) -------------------------------------------------
  const msg91Key = process.env.MSG91_AUTHKEY;
  const flowTemplateId = process.env.MSG91_FLOW_TEMPLATE_ID;
  if (msg91Key && flowTemplateId) {
    try {
      const res = await fetch("https://control.msg91.com/api/v5/flow/", {
        method: "POST",
        headers: { authkey: msg91Key, "Content-Type": "application/json" },
        body: JSON.stringify({
          template_id: flowTemplateId,
          short_url: "0",
          realTimeResponse: "1",
          recipients: [{ mobiles: mobile, var: opts.text }],
        }),
        cache: "no-store",
      });

      return await readMsg91Result(res, "MSG91_FLOW");
    } catch (err) {
      console.error("[sms] MSG91 flow request failed:", err);
      return { delivered: false, reason: "MSG91_FLOW_EXCEPTION" };
    }
  }

  // --- Twilio -----------------------------------------------------------
  const sid = process.env.TWILIO_ACCOUNT_SID;
  const token = process.env.TWILIO_AUTH_TOKEN;
  const from = process.env.TWILIO_FROM;
  if (sid && token && from) {
    try {
      const body = new URLSearchParams({ To: `+${mobile}`, From: from, Body: opts.text });
      const res = await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`, {
        method: "POST",
        headers: {
          Authorization: `Basic ${Buffer.from(`${sid}:${token}`).toString("base64")}`,
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body,
        cache: "no-store",
      });
      if (!res.ok) return { delivered: false, reason: `TWILIO_${res.status}` };
      return { delivered: true };
    } catch {
      return { delivered: false, reason: "TWILIO_EXCEPTION" };
    }
  }

  console.info(`[sms] not configured — would send to ${mobile}: ${opts.text}`);
  return { delivered: false, reason: "SMS_NOT_CONFIGURED" };
}
