-- Website Builder templates: new homepage section types. Adds enum values only.
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'BANNER_SLIDER';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'EXAM_SELECTOR';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'SEARCH';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'FREE_RESOURCES';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'PYQ_HUB';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'STUDY_MATERIAL';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'FREE_TESTS';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'TODAY_SCHEDULE';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'ATOMIC_GURU';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'YOUTUBE';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'WHY_US';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'TRUST';
